name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  country_pickers: ^2.0.0
  sms_autofill: ^2.3.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg_provider: ^1.0.7
  calendar_date_picker2: ^0.5.3
  intl: ^0.19.0
  http: 1.2.0
  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSansLight.ttf
          weight: 300
        - asset: assets/fonts/NunitoSansBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSansSemiBold.ttf
          weight: 600
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
